### ISSUE TITLE
Ch6 - Q1: How can an object be instantiated in JavaScript?

### ISSUE THREAD

**Issue by IEH-tekmexico** [shardool/JavaScript_Assignment_1#9]
Objects can also be created through a literal syntax:
* _{}_ creates a new plain object
* _[]_ creates an array object
* _function(){}_ creates a function, which is also an object

We can also use _Object.create()_.

**Comment by shardool** [comment]
I sure would have included these in my answer if the question was "What are the different ways of "creating" a JavaScript object (instead of How can an object be "instantiated" in JavaScript?) ?". To my mind, "instantiation" almost always involves invoking the constructor function with the "new" keyword" as it is the only way to create multiple "instances" off of an existing object.

**Comment by IEH-tekmexico** [comment]
In this case it would be synonymous. An object is an instance, and instantiation is creation. 
```javascript
var a1 = {}, a2 = new Object();
```
In both of these cases, the variables contain a new, plain object. Same for the following:
```javascript
var b1 = [], b2 = new Array();
var c1 = function(){}, c2 = new Function();
```

**Comment by shardool** [comment]
updated my answer to include the suggested points. Kindly review and close
